server:
  servlet:
    context-path: /api/mutant
  port: 8080
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, metrics